// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyCqz4Hs2-o72Odb5d_x7qbQ17BEwrL0eM0",
      authDomain: "fanbae-99a9e.firebaseapp.com",
      databaseURL: "https://fanbae-99a9e-default-rtdb.firebaseio.com",
      projectId: "fanbae-99a9e",
      storageBucket: "fanbae-99a9e.firebasestorage.app",
      messagingSenderId: "53658349575",
      appId: "1:53658349575:web:fdf844b2c7ea2932fabaa2",
      measurementId: "G-NM54QVPFMC");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyCqz4Hs2-o72Odb5d_x7qbQ17BEwrL0eM0",
    appId: '1:53658349575:android:ba5b5345a1227314fabaa2',
    messagingSenderId: '53658349575',
    projectId: 'fanbae-99a9e',
    storageBucket: 'fanbae-99a9e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt1EZhccYCZ7QcCCUGGkhOLpUP1yBnX8E',
    appId: '1:1061464771171:ios:2ebd2515622bb82e380656',
    messagingSenderId: '1061464771171',
    projectId: 'fir-2e48e',
    storageBucket: 'fir-2e48e.firebasestorage.app',
    androidClientId:
        '1061464771171-6pdkujv64jd2go0045h66lj4edrmshq9.apps.googleusercontent.com',
    iosClientId:
        '1061464771171-r179307a8bujtn8evmmvs1tg37k4cpri.apps.googleusercontent.com',
    iosBundleId: 'com.fanbae.tv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDv8lz2mfppOZhU4AH9F2pWx3Os6IcoACg',
    appId: '1:1061464771171:android:59cefd0a8ba63e52380656',
    messagingSenderId: '1061464771171',
    projectId: 'fir-2e48e',
    storageBucket: 'fir-2406c.firebasestorage.app',
    androidClientId:
        '946063364931-on7ef7qpcps70n63fvv34krka4hsvsun.apps.googleusercontent.com',
    iosClientId:
        '946063364931-mf45cskfiqtc63namugb7n5usvgm8vkq.apps.googleusercontent.com',
    iosBundleId: 'com.fanbae.tv',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyCqz4Hs2-o72Odb5d_x7qbQ17BEwrL0eM0",
    authDomain: "fanbae-99a9e.firebaseapp.com",
    projectId: "fanbae-99a9e",
    storageBucket: "fanbae-99a9e.firebasestorage.app",
    messagingSenderId: "53658349575",
    appId: "1:53658349575:web:fdf844b2c7ea2932fabaa2",
  );
}
